### ISSUE TITLE
cocoapods?

### ISSUE THREAD

**Issue by jafara** [lloydkeijzer/SwimpleInjection#1]

**Comment by lloydkeijzer** [comment]
Hi Jafara, SwimpleInjection only supports Swift Package Manager for now. Cocoapods is on the roadmap. I estimate it will be released somewhere next week. Thanks for your interrest😄

**Comment by lloydkeijzer** [comment]
I've looked into adding cocoapods and came to the conclusion it adds to much overhead by increasing the repo size, while SPM is the standard provided by Apple as a first party solution for dependency management. And it comes with the benefit of keeping the repo size low, which is one of the core values of the Swimple packages series. 

The MIT license allows forking the repo and adding the cocoapod intergration for private use. If there is any reason why you can't support SPM yet, it might be a solution that works for you.
